### ISSUE TITLE
Graph not rendering for large networks

### ISSUE THREAD

**Issue by FinScience** [datastorm-open/visNetwork#166]
Hi,

I have a network with 5157 nodes and 44488 edges. visNetwork is unable to render the graph and my R session is crashing. Is there any workaround for this. The reason for such a large graph is not to show complete information but the percentage of coverage based on different colors of the nodes and edges.

My system has 8 GB RAM

**Comment by bjstewart1** [comment]
I have this problem also, even when a layout is passed to visNetwork.

**Comment by bthieurmel** [comment]
``javascript`` in general, and so ``visNetwork`` using ``vis.js`` are great tools for visualization and interactivity, but with limits due to amount of data. For a large network, perhaps prefer a "static" way, with ``igraph`` of other.

To try to increase performance, you can test this way : 

http://datastorm-open.github.io/visNetwork/performance.html
