### ISSUE TITLE
Update graph on every iteration

### ISSUE THREAD

**Issue by abhik1368** [datastorm-open/visNetwork#202]
Hi ,

This is not an issue but i was wondering if you can suggest something how can i solve the problem. 
In the current applicaiton I  generate graphs based on database table which have person and its neighbours information. The graph gets generated but i want to expand the network based on click event keeping the oldnetwork as it is and the network like this will grow keeping the old network in the current interface . Can you suggest how can i implement such a solution ? Do you think caches can solve a problem ?

**Comment by FrissAnalytics** [comment]
In a shiny context you can use `visNetworkProxy` together with `visUpdateNodes` and `visUpdateEdges`.

First you create a regular visNetwork with an `id`. Via the proxy call you can subsequently update nodes and edges. The `id` is used to get access to the chart after it has been created.  

Also, make sure that *every* node and every edge in your network has a unique `id` (separate from the network id).

Capturing a click on an node is easy using `visEvents` or using the build in functionality, see [here](http://datastorm-open.github.io/visNetwork/shiny.html).

In an `observeEvent` call in shiny you can capture the click event and via `visNetworkProxy` together with `visUpdateNodes` and `visUpdateEdges` you can grow your network, given that on click you know which nodes and edges you want to add. 

Of note, when you add a node via `visUpdateNodes` which `id` does yet exist, it will be added automatically. If the `id` exists already in your network, that node will be updated. Removing of nodes, however, must be done separately via `visRemoveNodes`. The same applies to edges, which you can remove via `visRemoveEdges`.

Hence, during updates it makes sense in shiny to keep track of which nodes / edges are in your network, before and after updating. In the latest versions of visNetwork you can get information on the nodes and edges in the client via `visGetNodes` and `visGetEdges `.

With these ingredients you can implement the scheme you want.

**Comment by bthieurmel** [comment]
@FrissAnalytics give you all the functions and tips to play and update a network. Have to look to ``?visNetworkProxy`` to see all available function.

**Comment by abhik1368** [comment]
Yes thank for the tips does the network_proxy object updates by itself when we call second time. Would certainly appreciate  if you can give an example for 2-4 iterations ?

**Comment by FrissAnalytics** [comment]
You have two options. Either you use the render function `renderVisNetwork` and pass a new node and edge data frame, from which a new graph is generated from scratch. Otherwise, in an `observeEvent` block you listen for changes to some data reactive and update the network as described above. 

If this is still unclear to you, consider studying the `leafet` example by RSTUDIO. You can find the code here: https://rstudio.github.io/leaflet/shiny.html. Specifically, look at their use of the `leafletProxy` function. 

In the example shown [here](https://rstudio.github.io/leaflet/shiny.html#modifying-existing-maps-with-leafletproxy) you'll find an example that uses (i) a reactive dataset, (ii) an initial render call via  `output$map <- renderLeaflet({ ... })` that uses the reactive data and finally, (iii) two separate `observe` blocks that use `leafletProxy`.

Of note, `leafletProxy` is just a way to get access to an already existing leaflet map, created in step (i).

Even though this code is different and deals with maps instead of networks, the principles are very similar and even the function names are similar i.e. `render` functions and `proxy` functions. 

In case it is still unclear it's probably best to invest a bit more time in understanding shiny and reactivity, which RSTUDIO tutorials you can find [here](https://shiny.rstudio.com/tutorial/).

**Comment by ankitachow** [comment]
I'm trying to update an edge with a different color when the edge is clicked.
I'm using the below code but getting an error in visUpdated Edges. Can someone tell what I'm doing wrong.
` visEvents(click = "function(edges) {
                 Shiny.onInputChange('edge_data', edges.edges[0]);
             ;}")`
`visNetworkProxy('network') %>%
      visUpdateEdges(id=input$edge_data$id, color = list(color = "red", highlight = "yellow"))`

**Comment by bthieurmel** [comment]
As wrote in the documentation, ``visUpdateEdges`` needs a data.frame : 

````
Usage

visUpdateEdges(graph, edges, legend = FALSE)

graph  : a visNetworkProxy object
edges  : data.frame with the information of edges. 
See visEdges....
````

So : 
````
observe({
     tmp <- input$edge_data$id
     if(!is.null(tmp)){
       data <- data.frame(id = tmp, color.color = "red", color.highlight = "yellow")
       visNetworkProxy('network') %>% visUpdateEdges(data)
     }
})
````
