### ISSUE TITLE
Collapsible network trees

### ISSUE THREAD

**Issue by DataStrategist** [datastorm-open/visNetwork#83]
Hi! So https://bl.ocks.org/mbostock/1062288 (which granted... uses D3) allows for nodes to collapse all it's edges `onClick`. Could something like that be implemented in visNetwork?

**Comment by bthieurmel** [comment]
Yes, perhaps one day, but not so simple to do !

**Comment by bthieurmel** [comment]
Hi,

A V0 first options is available on dev version if interested to test. ``visOptions``, new argument ``collapse``. Documented but examples missing at moment...

**Comment by mexindian** [comment]
```
devtools::install_github("datastorm-open/visNetwork",force = T)
Downloading GitHub repo datastorm-open/visNetwork@master
from URL https://api.github.com/repos/datastorm-open/visNetwork/zipball/master
Error in eapply(ns_env(pkg), force, all.names = TRUE) : 
  lazy-load database 'D:/Dropbox/R/library/visNetwork/R/visNetwork.rdb' is corrupt
In addition: Warning messages:
1: In eapply(ns_env(pkg), force, all.names = TRUE) :
  restarting interrupted promise evaluation
2: In eapply(ns_env(pkg), force, all.names = TRUE) :
  internal error -3 in R_decompress1
```

**Comment by bthieurmel** [comment]
Try unloading package before / restarting R session.

**Comment by mexindian** [comment]
Correct. Sorry!

OK, I've messed around with it a bit but don't seem to understand how to trigger the activity. Whether I try 
`visNetwork(nodes, edges) %>% visOptions(collapse = TRUE)`

or

`visNetwork(nodes, edges) %>% visOptions(collapse = FALSE)`

The result seems to be the same. Sorry, I'm having trouble visualizing how you want me to use the `fit`, `unselect`, and `clusterOptions` parameters...

What I was thinking is that perhaps having some kind of "visibility" boolean feature on the NODES df would let me assign a default "visible" or "collapsed" status, and then clicking on each node would toggle the visibility of all the connected nodes whose status was originally set to collapsed. Of course the whole option could be turned off by your new `visOptions` `collapse` thingie. So what I'm thinking:
Let's say this is my network:

![image](https://cloud.githubusercontent.com/assets/8094091/23360461/42e22e16-fce3-11e6-8ee0-9e5a86895e0d.png)

And let's say that this is how I had set the visibilities in the NODES df:
![image](https://cloud.githubusercontent.com/assets/8094091/23360479/61856798-fce3-11e6-87f9-67990f9ce4c5.png)

So the checkmark would show as visible and the crosses would show as collapsed by default. 

So when the visNetwork loaded, it would ONLY show "Label 7". Then, clicking on "Label 7" would show "Label 2" and "Label 5". Clicking "Label 7" again would hide them. Clicking on "Label 5" would enable "Label 8", clicking again would collapse "Label 8" and "Label 2", and clicking on it a third time would show again 8 and 2. Clicking on "Label 5" would never change the visibility of "Label 7" because in the nodes df it was set as "visible", and therefore will never collapse.

What do you think?

**Comment by bthieurmel** [comment]
```collapse`` options at moment allow user to cluster all ``connected to`` nodes double-clicking on one node, and re-open double-clicking too.

``fit`` is to enable a fit zoom after collapse action, ``unselect`` to disable click-event & highlight with double-clik, and ``clusterOptions`` to control node appearance after collapsed.

**Comment by mexindian** [comment]
ah! I discovered it! Just need to add in the documentation that you trigger the collapse event using DOUBLE click! I was trying single click and nothing was happening. Pefect! Here's my comments:
I think `fit` should default FALSE... it's too shaky otherwise. 
`unselect` doesn't seem to work perfectly? If I run: `visNetwork(nodes, edges) %>% visOptions(collapse = list(enabled=T,fit=F,unselect=T))` and doubleclick on LABEL 7, it still stays highlighted. However after I doubleclick again, then it correctly unselects.

and  `clusterOptions` works perfectly! Test: `visNetwork(nodes, edges) %>% visOptions(collapse = list(enabled=T,fit=F,unselect=T, clusterOptions=list(color="pink",size=100,shape="diamond")))`

I'm not fully sure of the clustering algorithm... in terms of what nodes get clustered when you click on a long chain. I guess it clusters towards nodes with a lower centrality? If so, then this is correct!

So this implementation is very very good! The only thing I think is missing is to spawn the network with already some nodes clustered at the onset. I think this is very important for displaying large networks and allowing users to interact. Could this somehow depend on an argument set in the NODES df like I was mentioning? Either way, excellent work thus far!

**Comment by bthieurmel** [comment]
Hi,

Thanks for test and returns.

``unselect`` is util in case of highlight. It's not really a unselection of nodes, but a reset of highlight. I"m going to change to ```resetHighlight`` or other.

For algorithm, just take all ``to`` nodes, and continue until end. Better look on hierarchical network. Can add edge arrow to see.

````
visNetwork(nodes, edges) %>% visOptions(highlightNearest = T, collapse = list(enabled=T, fit=F, unselect=T)) %>%
  visEdges(arrows = "to")
````

**Comment by mexindian** [comment]
Perfect! Fully agree. You can use those as examples... or if you want, I can PR the manual with examples nicely written and documented? It's the least I can do.

And what about the precollapsed nodes issue? Shall we finish and close this one and I open another issue? Or how would you like it?

**Comment by bthieurmel** [comment]
I'am going to finish the job before next CRAN version , writing some examples and trying to add precollapsed nodes.

**Comment by FrissAnalytics** [comment]
hi! 

really nice new feature! Is it also possible to trigger this "collapse" behaviour via a proxy function, in case for instance the double click event is already coupled to some other behaviour? 

For instance, I have a right click (context) event, that when clicked on a node subsequently shows a small list of options to the user. It would be nice to have one of these to say "collapse", in the sense that the above code does

In that scenario it would be nice to have a proxy function to trigger this behaviour for a given node id. 

Perhaps this is already available via the `visClusteringByConnection` option, but from the docs it not completely clear to me. 

best H

 


 if you create a right click context event that 

best Herman

**Comment by bthieurmel** [comment]
Hi,

``collapse`` features are now available via proxy using : 

- ``visOptions`` directly
- new ``visCollapse`` and ``visUncollapse``

And you can enable/disable the open cluster event like this : 

````
visNetworkProxy("network_id") %>% visEvents(type = "off", doubleClick = "networkOpenCluster")
visNetworkProxy("network_id") %>% visEvents(type = "on", doubleClick = "networkOpenCluster")
````

Add also some examples in demo shiny applications.

**Comment by mexindian** [comment]
I gave a PR to help test this feature... it seems you're getting close to solving the collapse nodes by default... but it seems for now you're only going to offer this functionality in shiny?

**Comment by bthieurmel** [comment]
Hi,
It's easy to collapse/uncollapsed nodes unsing shiny & proxy. I think it's not really possible to do that before rendering network.... This a example app : 

````

library(shiny)
library(visNetwork)

# Define UI for application that draws a histogram
ui <- shinyUI(fluidPage(
  actionButton("goCol", "Collapsed !"),
  actionButton("goUC", "uncollapse!"),
  actionButton("goRm", "remove event!"),
  actionButton("goAdd", "add event!"),
  visNetworkOutput("distPlot")
      
))

# Define server logic required to draw a histogram
server <- shinyServer(function(input, output) {
   
   output$distPlot <- renderVisNetwork({
     set.seed(125)
     nodes <- data.frame(id = 1:15, label = paste("Label", 1:15),
                         group = sample(LETTERS[1:3], 15, replace = TRUE))
     
     edges <- data.frame(from = trunc(runif(15)*(15-1))+1,
                         to = trunc(runif(15)*(15-1))+1)

     visNetwork(nodes, edges) %>% visOptions(highlightNearest = T, collapse = T) %>% visEdges(arrows = "to")
     
   })
   
   observe({
     if(input$goCol > 0){
       visNetworkProxy("distPlot") %>% visCollapse(nodes = c(10,3), clusterOptions = list( shape ="square", label = "and so ?"))
     }
   })
   
   observe({
     if(input$goUC > 0){
       visNetworkProxy("distPlot") %>% visUncollapse()
     }
   })
   
   observe({
     if(input$goRm > 0){
       visNetworkProxy("distPlot") %>% visEvents(type = "off", doubleClick = "networkOpenCluster")
     }
   })
   
   observe({
     if(input$goAdd > 0){
       visNetworkProxy("distPlot") %>% visEvents(type = "on", doubleClick = "networkOpenCluster")
     }
   })
   
})

# Run the application 
shinyApp(ui = ui, server = server)
````

Linked to your question on PR : for me it's good with several nodes on ``visCollapse``. The fact is the process is sequential.

**Comment by mexindian** [comment]
Hrm... just had an idea. If we could just get rid of the sequential requirement, we could always depend on shiny bookmark state to make networks "load in collapsed state" (to the degree that there's an input somwhere saying what should be collapsed). But it would only work once... so not a great solution...
